# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMapp', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('direction', models.BooleanField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMapp.Contact')),
            ],
        ),
    ]
