# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMapp', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.FileField(upload_to=b'', verbose_name='icon/'),
        ),
    ]
