# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMapp', '0005_auto_20160503_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='direction',
        ),
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
