# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMapp', '0008_message_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='state',
        ),
    ]
